# Generated by Django 4.2.25 on 2025-10-13 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asin', 'timestamp'], name='myapp_price_asin_6f0802_idx')],
            },
        ),
    ]
